# Generated by Django 5.1.6 on 2025-02-28 21:02

import django.db.models.deletion
import ipam.fields
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country_code', models.CharField(blank=True, max_length=100, unique=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='netbox_geoip_country', to='extras.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeoIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('subnet', ipam.fields.IPNetworkField()),
                ('object_id', models.PositiveBigIntegerField()),
                ('type', models.CharField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('subdivision_code', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='netbox_geoip.country')),
                ('object_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'ipam'), ('model', 'prefix')), models.Q(('app_label', 'ipam'), ('model', 'ipaddress')), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'NETBOX GEOIP',
                'ordering': ['subnet', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('subdivision_code', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='netbox_geoip_regions', to='netbox_geoip.country')),
                ('tags', models.ManyToManyField(blank=True, related_name='netbox_geoip_region', to='extras.tag')),
            ],
            options={
                'unique_together': {('country', 'name')},
            },
        ),
    ]
