# Generated by Django 5.2.7 on 2025-11-07 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_geoip', '0005_update_ipam_urls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['country', 'name']},
        ),
        migrations.RemoveField(
            model_name='geoip',
            name='created',
        ),
        migrations.RemoveField(
            model_name='geoip',
            name='custom_field_data',
        ),
        migrations.RemoveField(
            model_name='geoip',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='geoip',
            name='tags',
        ),
        migrations.AlterField(
            model_name='geoip',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='netbox_geoip_geoip', to='netbox_geoip.country'),
        ),
    ]
